# JS13 - PRAKTIKUM 1

In [1]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi hidden layer 2:")
print(a2)

Epoch 0, Loss: 0.34016945954404565
Epoch 1000, Loss: 0.16583796269484408
Epoch 2000, Loss: 0.14226909292246878
Epoch 3000, Loss: 0.13508973754921605
Epoch 4000, Loss: 0.13194639860986512
Epoch 5000, Loss: 0.13023651423797206
Epoch 6000, Loss: 0.1291764578945538
Epoch 7000, Loss: 0.12846037981422792
Epoch 8000, Loss: 0.12794661753586717
Epoch 9000, Loss: 0.12756123561279198
Prediksi hidden layer 2:
[[0.04101453]
 [0.49748078]
 [0.95741687]
 [0.50301931]]


# JS13 - TUGAS 1

Change hidden layer from 2 to 3

In [2]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3  # Changed from 2 to 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi hidden layer 3 :")
print(a2)

Epoch 0, Loss: 0.2564002180228986
Epoch 1000, Loss: 0.23710530732856822
Epoch 2000, Loss: 0.19599553654733487
Epoch 3000, Loss: 0.14453520948289747
Epoch 4000, Loss: 0.043504804226466784
Epoch 5000, Loss: 0.01574663244407889
Epoch 6000, Loss: 0.008638169555738732
Epoch 7000, Loss: 0.0057517337711503625
Epoch 8000, Loss: 0.004246111392023245
Epoch 9000, Loss: 0.003337799406952424
Prediksi hidden layer 3 :
[[0.04571243]
 [0.95016646]
 [0.94993423]
 [0.0621814 ]]


Implement ReLu

In [3]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi Sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Fungsi aktivasi ReLU
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)  # ReLU for hidden layer
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2) # Sigmoid for output layer

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2) # Sigmoid derivative for output
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(z1) # ReLU derivative for hidden layer, applied to z1
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
# Recalculate a1 and a2 for final prediction using the trained weights
z1_final = np.dot(X, W1) + b1
a1_final = relu(z1_final)
z2_final = np.dot(a1_final, W2) + b2
a2_final = sigmoid(z2_final)

final_loss = np.mean(np.square(y - a2_final))
print("Prediksi:")
print(a2_final)
print(f"Final Loss (ReLU hidden, Sigmoid output): {final_loss}")

Epoch 0, Loss: 0.2617013640670741
Epoch 1000, Loss: 0.16734002527732458
Epoch 2000, Loss: 0.16685901461605238
Epoch 3000, Loss: 0.16678616589045694
Epoch 4000, Loss: 0.16673900700614094
Epoch 5000, Loss: 0.1667232910938093
Epoch 6000, Loss: 0.16671553465859015
Epoch 7000, Loss: 0.16670738636102067
Epoch 8000, Loss: 0.16669754352526325
Epoch 9000, Loss: 0.16669244482115037
Prediksi:
[[0.66652323]
 [0.66652323]
 [0.66652323]
 [0.00965677]]
Final Loss (ReLU hidden, Sigmoid output): 0.1666899953769525
